# --- SOCIOS ---
listar-socios=SELECT * FROM socio;
listar-socios-con-patron=SELECT * FROM socio WHERE titulo_patron=1;
listar-socios-sin-patron=SELECT * FROM socio WHERE titulo_patron=0;
insertar-socio=INSERT INTO socio (dni, nombre, apellidos, fecha_nacimiento, direccion,titulo_patron ,id_inscripcion,cuota_inscripcion, fecha_inscripcion) VALUES (?, ?, ?, ?, ?, ?, ?, ?,?);
existe-socio=SELECT COUNT(*) FROM socio WHERE dni = ?;
actualizar-socio=UPDATE socio SET nombre=?, apellidos=?, fecha_nacimiento=?, direccion=?, titulo_patron=?, fecha_inscripcion=? WHERE dni=?;
actualizar-titulo-patron=UPDATE socio SET titulo_patron = ? WHERE dni = ?;
select-titulo-patron=SELECT titulo_patron FROM socio WHERE dni = ?;
buscar-socio-por-dni = SELECT * FROM socio WHERE dni = ?
insertar-conyuge = INSERT INTO conyuge (dni_titular, dni_conyuge, nombre, apellidos, fecha_nacimiento, direccion) VALUES (?, ?, ?, ?, ?, ?);
insertar-hijo=INSERT INTO familiares (dni_socio, dni_hijo) VALUES (?, ?);
buscar-conyuge = SELECT * FROM socio WHERE cuota_inscripcion = 250 AND id_inscripcion = ?;
buscar-hijo=SELECT * FROM socio WHERE cuota_inscripcion = 100 AND id_inscripcion = ?;
listar-todos-socios-con-detalles=SELECT s.dni, s.nombre, s.apellidos, s.fecha_nacimiento, s.direccion, s.titulo_patron, s.fecha_inscripcion, s.id_inscripcion FROM socio s;
insertar-inscripcion=INSERT INTO inscripcion (tipo) VALUES (?);
listar-inscripciones=SELECT * FROM inscripcion;


# --- EMBARCACIONES Y PATRONES---
insertar-embarcacion=INSERT INTO embarcacion (matricula, tipo, nombre, num_plazas) VALUES (?, ?, ?, ?);
listar-embarcacion-por-tipo=SELECT * FROM embarcacion WHERE tipo = ?;
insertar-patron=INSERT INTO patron (dni_patron, nombre, apellido, fecha_nacimiento) VALUES (?, ?, ?, ?);
existe-patron=SELECT COUNT(*) FROM patron WHERE dni_patron = ?;
listar-patrones=SELECT * FROM patron;
actualizar-patron=UPDATE patron SET nombre = ?, apellido = ?, fecha_nacimiento = ? WHERE dni_patron = ?;
asignar-patron-embarcacion=INSERT INTO asignacion (fecha_asignacion,fecha_fin,matricula, dni_patron) VALUES (?, ?,?,?);
check-embarcacion-solapamiento-open=SELECT COUNT(*) FROM asignacion WHERE matricula = ? AND (fecha_fin IS NULL OR fecha_fin >= ?);
check-embarcacion-solapamiento-range=SELECT COUNT(*) FROM asignacion WHERE matricula = ? AND NOT (fecha_fin < ? OR fecha_asignacion > ?);
listar-patron-embarcacion=SELECT * FROM asignacion;
actualizar-patron = UPDATE patron SET nombre = ?, apellido = ?, fecha_nacimiento = ? WHERE dni_patron = ?

# # --- INSCRIPCION ---
# insertar-inscripcion=INSERT INTO inscripcion (tipo) VALUES (?);
# existe-inscripcion=SELECT COUNT(*) FROM inscripcion WHERE id = ?;
# listar-inscripciones=SELECT * FROM inscripcion;
# actualizar-inscripcion=UPDATE inscripcion SET tipo = ? WHERE id = ?;


# --- ALQUILER ---

insertar-alquiler=INSERT INTO alquiler (matricula, num_pasajeros, importe_total, dni_socio, fecha_inicio, fecha_fin) VALUES (?, ?, ?, ?, ?, ?);
check-alquiler-range=SELECT COUNT(*) FROM alquiler WHERE matricula = ? AND NOT (fecha_fin < ? OR fecha_inicio > ?);
select-embarcacion-num-plazas=SELECT num_plazas FROM embarcacion WHERE matricula = ?;
listar-alquileres=SELECT * FROM alquiler;
listar-embarcaciones-disponibles-por-fecha=SELECT matricula FROM embarcacion e WHERE NOT EXISTS (SELECT 1 FROM alquiler a WHERE a.matricula = e.matricula AND NOT (a.fecha_fin < ? OR a.fecha_inicio > ?));
insertar-socio-alquiler=INSERT INTO socio_alquiler (dni, id_alquiler) VALUES (?, ?);
listar-socio-alquiler=SELECT * FROM socio_alquiler;
select-embarcacion-num-plazas-by-alquiler=SELECT e.num_plazas FROM alquiler a JOIN embarcacion e ON a.matricula = e.matricula WHERE a.id_alquiler = ?
count-socios-por-alquiler=SELECT COUNT(*) FROM socio_alquiler WHERE id_alquiler = ?
existe-socio-en-alquiler=SELECT COUNT(*) FROM socio_alquiler WHERE dni = ? AND id_alquiler = ?
select-num-pasajeros-by-alquiler=SELECT num_pasajeros FROM alquiler WHERE id_alquiler = ?
listar-socios-por-alquiler=SELECT s.dni, s.nombre, s.apellidos, s.fecha_nacimiento, s.direccion, s.titulo_patron, s.fecha_inscripcion FROM socio s JOIN socio_alquiler sa ON s.dni = sa.dni WHERE sa.id_alquiler = ? ORDER BY s.apellidos, s.nombre
# ---P2---
select-alquiler-by-id=SELECT * FROM alquiler WHERE id_alquiler = ?
listar-alquileres-futuros=SELECT * FROM alquiler WHERE fecha_inicio > ?
# ---P2 semana2---
insertar-socio-alquiler=INSERT INTO socio_alquiler (dni, id_alquiler) VALUES (?, ?);
eliminar-socio-alquiler=DELETE FROM socio_alquiler WHERE dni = ? AND id_alquiler = ?;
eliminar-alquiler=DELETE FROM alquiler WHERE id_alquiler = ?;





# --- RESERVA ---
insertar-reserva=INSERT INTO reserva (id,fecha, dni_socio, matricula, importe_reserva, num_pasajeros_reserva,descripcion_reserva) VALUES (?, ?, ?, ?, ?,?,?);
check-reserva-range=SELECT COUNT(*) FROM reserva WHERE matricula = ? AND (fecha BETWEEN ? AND ?);
select-embarcacion-num-plazas-reserva=SELECT num_plazas FROM embarcacion WHERE matricula = ?;
listar-reservas=SELECT * FROM reserva;

listar-embarcaciones-disponibles-por-fecha=SELECT matricula FROM embarcacion WHERE matricula NOT IN (SELECT matricula FROM reserva WHERE fecha BETWEEN ? AND ?);

# --- PRACTICA 2 ---

# --- apartado a ---
listar-inscripciones-por-tipo=SELECT * FROM inscripcion WHERE tipo = ?;
obtener-inscripcion-por-dni=SELECT i.id, i.tipo FROM inscripcion i JOIN socio s ON i.id = s.id_inscripcion WHERE s.dni = ?;
actualizar-socio=UPDATE socio SET nombre=?, apellidos=?, fecha_nacimiento=?, direccion=?, titulo_patron=?, cuota_inscripcion=?, fecha_inscripcion=?, id_inscripcion=? WHERE dni=?;
actualizar-tipo-inscripcion=UPDATE inscripcion SET tipo=? WHERE id=?;
buscar-inscripcion-por-id=SELECT id, tipo FROM inscripcion WHERE id=?;
update-socio-inscripcion=UPDATE socio SET id_inscripcion=?, cuota_inscripcion=? WHERE dni=?;
desvincular-socio-de-inscripcion=UPDATE socio SET id_inscripcion=NULL, cuota_inscripcion=0.0 WHERE dni=?;
desvincular-socios=UPDATE socio SET id_inscripcion=NULL, cuota_inscripcion=0.0 WHERE id_inscripcion=?;
eliminar-socio-sin-inscripcion=DELETE FROM socio WHERE dni=? AND id_inscripcion IS NULL;
eliminar-inscripcion = DELETE FROM inscripcion WHERE id = ?;
delete-inscripcion-por-id=DELETE FROM inscripcion WHERE id=?;




# --- apartado b ---
# Consultas para eliminar una embarcación
delete-embarcacion=DELETE FROM embarcacion WHERE matricula = ?;

# Consultas para eliminar un patrón
delete-patron=DELETE FROM patron WHERE dni_patron = ?;

# Consultas para eliminar la asignación de un patrón a una embarcación
remove-patron-from-embarcacion=DELETE FROM asignacion WHERE matricula = ? AND dni_patron = ?;

# Consultas para verificar si una embarcación está vinculada a un alquiler o reserva
check-embarcacion-linked-to-alquiler-reserva=SELECT COUNT(*) FROM alquiler WHERE matricula = ? OR reserva WHERE matricula = ?;

# Consultas para verificar si un patrón está vinculado a una embarcación
check-patron-linked-to-embarcacion=SELECT COUNT(*) FROM asignacion WHERE dni_patron = ?;
actualizar-embarcacion=UPDATE embarcacion SET tipo = ?, nombre = ?, num_plazas = ? WHERE matricula = ?;
find-embarcacion-by-matricula=SELECT * FROM embarcacion WHERE matricula = ?
buscar-embarcacion-por-matricula=SELECT matricula, tipo, nombre, num_plazas FROM embarcacion WHERE matricula = ?
buscar-patron-por-dni=SELECT dni_patron, nombre, apellido, fecha_nacimiento FROM patron WHERE dni_patron = ?






# --- apartado d ---
listar-reservas-futuras=SELECT * FROM reserva WHERE fecha > ?;
obtener-reserva-por-id=SELECT * FROM reserva WHERE id = ?;
update-reserva-fecha=UPDATE reserva SET fecha = ? WHERE id = ?;
update-reserva-datos=UPDATE reserva SET descripcion_reserva = ?, num_pasajeros_reserva = ?, fecha = ? WHERE id = ?;
eliminar-reserva=DELETE FROM reserva WHERE id = ?;
check-reserva-range=SELECT COUNT(*) FROM reserva WHERE matricula = ? AND fecha BETWEEN ? AND ?;
select-embarcacion-num-plazas=SELECT num_plazas FROM embarcacion WHERE matricula = ?;
verificar-disponibilidad=SELECT COUNT(*) FROM reserva WHERE matricula = ? AND fecha = ?;





# --- apartado b ---
listar-embarcaciones=SELECT matricula, tipo, nombre, num_plazas FROM embarcacion;